In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype="int64")
b = np.array([1,2,3], dtype="int64")
c = np.array([[[[1],[2],[3]],[[4],[2],[5]]],[[[1],[2],[3]],[[4],[2],[5]]],[[[1],[2],[3]],[[4],[2],[5]]],[[[1],[2],[3]],[[4],[2],[5]]]], dtype="int64")
print(a * b)

[1 4 9]


In [4]:
c.ndim

4

In [5]:
c.shape

(4, 2, 3, 1)

In [6]:
c.itemsize

8

In [7]:
c.size

24

In [8]:
c.nbytes

192

In [9]:
c.size * c.itemsize

192

In [10]:
c.dtype

dtype('int64')

In [11]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.20161322e-306],
       [1.89146896e-307, 7.56571288e-307]])

In [12]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="int32")
d[0:3:2,0:3:2]

array([[1, 3],
       [7, 9]])

In [13]:
nums = np.zeros((2,3,3), dtype="int64")
nums

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [14]:
nums[0][0][0] += 18
nums

array([[[18,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=int64)

In [15]:
np.full((2,2,2),100,dtype="int64")

array([[[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]]], dtype=int64)

In [16]:
np.random.rand(4,2,3)

array([[[0.86173993, 0.38888984, 0.24634393],
        [0.19318483, 0.29902834, 0.35846245]],

       [[0.8523837 , 0.69335166, 0.2048272 ],
        [0.77752638, 0.2911788 , 0.48617923]],

       [[0.63837159, 0.96394405, 0.3589091 ],
        [0.38919447, 0.77071924, 0.43197509]],

       [[0.45159663, 0.50930587, 0.29674334],
        [0.42793097, 0.16026373, 0.17473977]]])

In [17]:
np.random.random_sample((4,2,5))

array([[[0.62499379, 0.89084813, 0.73623361, 0.73365646, 0.32662559],
        [0.03174302, 0.29136749, 0.83543012, 0.83293113, 0.74931638]],

       [[0.70362459, 0.6344972 , 0.91152937, 0.24810443, 0.04213938],
        [0.07565705, 0.59503721, 0.20358992, 0.9793194 , 0.47099079]],

       [[0.16275465, 0.70432184, 0.02568124, 0.98244358, 0.84915281],
        [0.32806533, 0.56667809, 0.96412368, 0.35417841, 0.83692981]],

       [[0.68093139, 0.10781883, 0.64585965, 0.24472416, 0.30242538],
        [0.86122333, 0.69267322, 0.23191105, 0.84870503, 0.01884583]]])

In [18]:
np.random.random_sample(a.shape)

array([0.52480038, 0.36245043, 0.09418129])

In [19]:
np.random.randint(100,1000,size=(4,2,5))

array([[[722, 434, 348, 746, 767],
        [661, 315, 257, 463, 489]],

       [[582, 823, 638, 552, 271],
        [884, 820, 960, 893, 785]],

       [[721, 916, 989, 814, 668],
        [700, 736, 469, 551, 903]],

       [[973, 920, 303, 161, 155],
        [848, 235, 621, 207, 213]]])

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]
                ,[[10,11,12],[13,14,15],[16,17,18]],
                [[19,20,21],[22,23,24],[25,26,27]]], dtype="float64")
r = np.repeat(arr, 2, axis=1)
print(r)

[[[ 1.  2.  3.]
  [ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [10. 11. 12.]
  [13. 14. 15.]
  [13. 14. 15.]
  [16. 17. 18.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [19. 20. 21.]
  [22. 23. 24.]
  [22. 23. 24.]
  [25. 26. 27.]
  [25. 26. 27.]]]


In [22]:
arr = arr + 2

In [23]:
arr[0] = arr[0] + 3
arr

array([[[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [24]:
arr[1] *= 2
arr

array([[[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]],

       [[24., 26., 28.],
        [30., 32., 34.],
        [36., 38., 40.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [25]:
arr[2] = arr[2] / 2.0
arr

array([[[ 6. ,  7. ,  8. ],
        [ 9. , 10. , 11. ],
        [12. , 13. , 14. ]],

       [[24. , 26. , 28. ],
        [30. , 32. , 34. ],
        [36. , 38. , 40. ]],

       [[10.5, 11. , 11.5],
        [12. , 12.5, 13. ],
        [13.5, 14. , 14.5]]])

In [26]:
arr ** 3

array([[[  216.   ,   343.   ,   512.   ],
        [  729.   ,  1000.   ,  1331.   ],
        [ 1728.   ,  2197.   ,  2744.   ]],

       [[13824.   , 17576.   , 21952.   ],
        [27000.   , 32768.   , 39304.   ],
        [46656.   , 54872.   , 64000.   ]],

       [[ 1157.625,  1331.   ,  1520.875],
        [ 1728.   ,  1953.125,  2197.   ],
        [ 2460.375,  2744.   ,  3048.625]]])

In [27]:
np.tan(arr ** 3)

array([[[-0.96946093,  0.63590226, -0.0797711 ],
        [ 0.15165115,  1.47032416, -1.68536221],
        [ 0.12468063,  1.65299212,  5.45875744]],

       [[ 1.53142425, -2.65753814, -8.20129398],
        [ 2.25098887,  2.48796518, -0.50255443],
        [ 0.21053186,  1.37706119, -0.57994005]],

       [[19.25317761, -1.68536221,  0.35841945],
        [ 0.12468063, -1.38554709,  1.65299212],
        [ 0.55667332,  5.45875744,  3.34288359]]])

In [28]:
np.tan(140000, dtype="float64")

2.623113019913872

In [29]:
a = np.ones((2,3), dtype="int64")
b = np.full((3,2), 4, dtype="int64")
c = np.matmul(a,b)
c

array([[12, 12],
       [12, 12]], dtype=int64)

In [30]:
#find the determinant
np.linalg.det(c)

0.0

In [31]:
d = np.identity(6)
np.linalg.det(d)

1.0

In [32]:
a = np.array([[1,1,6,4],[2,3,5,0],[5,2,4,3]])
np.min(a, axis=0)

array([1, 1, 4, 0])

In [33]:
np.min(a, axis=1)

array([1, 0, 2])

In [34]:
np.min(a)

0

In [35]:
np.max(a)

6

In [36]:
np.max(a, axis=0)

array([5, 3, 6, 4])

In [37]:
np.max(a, axis=1)

array([6, 5, 5])

In [38]:
a.reshape((2,2,3))

array([[[1, 1, 6],
        [4, 2, 3]],

       [[5, 0, 5],
        [2, 4, 3]]])

In [39]:
b = np.array([1,2,3,4])
np.vstack([a,b,a])

array([[1, 1, 6, 4],
       [2, 3, 5, 0],
       [5, 2, 4, 3],
       [1, 2, 3, 4],
       [1, 1, 6, 4],
       [2, 3, 5, 0],
       [5, 2, 4, 3]])

In [40]:
data = np.genfromtxt('data.txt', delimiter=',',dtype="int64")

In [41]:
data[data>15]

array([16, 17, 18, 19, 20], dtype=int64)

In [42]:
data[[1,0]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int64)

In [43]:
new = np.array([1,2,3,4,5,6])
new[[0,1,5]]

array([1, 2, 6])

In [44]:
print(data)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [45]:
np.all(data < 15, axis=0)

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [46]:
np.all(data < 15, axis=1)

array([ True, False])

In [47]:
np.random.random((3,2))

array([[0.60508241, 0.26741689],
       [0.91282925, 0.95867512],
       [0.39445657, 0.81678107]])

In [48]:
print(np.random.uniform((1,100)))

[1.         3.24376203]


In [49]:
np.random.normal(0,1,10)

array([-1.17861944,  0.65636771,  0.20295104, -0.31068399, -1.54237471,
        1.89188444,  0.57362734,  1.92891117, -0.36695771,  1.14682686])

In [50]:
np.diag(np.array([1,2,3,5,4]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [51]:
np.diag([1,2,3,5,4])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [52]:
np.diag([1,2,3,5,4],k=3)

array([[0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
np.count_nonzero(np.diag([1,2,3,5,4],k=3)) # number of non_zeros

5

In [54]:
np.diag([1,2,3,5,4],k=3).size - np.count_nonzero(np.diag([1,2,3,5,4],k=3)) # number of zeros

59

In [55]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
x[True]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [57]:
x[[True,False,True]]

array([[1, 2, 3],
       [7, 8, 9]])

In [58]:
x * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [59]:
np.add.reduce(np.arange(2,8))

27

In [60]:
np.multiply.reduce(np.arange(2,8))

5040

In [61]:
np.subtract.reduce(np.arange(2,8))

-23

In [62]:
np.multiply.outer(np.arange(2,8),np.arange(2,8))

array([[ 4,  6,  8, 10, 12, 14],
       [ 6,  9, 12, 15, 18, 21],
       [ 8, 12, 16, 20, 24, 28],
       [10, 15, 20, 25, 30, 35],
       [12, 18, 24, 30, 36, 42],
       [14, 21, 28, 35, 42, 49]])

In [63]:
np.add.accumulate(np.arange(2,8)) #prefix sum

array([ 2,  5,  9, 14, 20, 27])

In [66]:
np.multiply.accumulate(np.arange(2,8)) # 2 * 3 * 4 * 5 * 6 * 7 

array([   2,    6,   24,  120,  720, 5040])